name: BIS Trainer CI Pipeline

on:
  push:
    branches:
      - main
      - CICD_Branch1
  pull_request:
    branches:
      - CICD_Branch1

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        node-version: [16.13.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.1
          run_install: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Cache PNPM dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
            
      - name: Install dependencies (if needed)
        working-directory: ./v1/views
        shell: pwsh
        run: |
          if (!(Test-Path "node_modules")) {
            Write-Host "Installing dependencies..."
            pnpm install --frozen-lockfile --ignore-scripts
          } else {
            Write-Host "Dependencies already installed, skipping..."
          }
      - name: Detect changed modules
        id: detect-changes
        working-directory: ./v1/views
        shell: pwsh
        run: |
          $lastCommit = (git rev-parse HEAD~1)
          $changedFiles = git diff --name-only $lastCommit HEAD
          $changedModules = @()
          $modules = Get-ChildItem -Directory | Where-Object { Test-Path "$_\src\package.json" } | Select-Object -ExpandProperty Name
          foreach ($module in $modules) {
            if ($changedFiles -match "v1/views/$module/") {
              $changedModules += $module
            }
          }
          if ($changedModules.Count -eq 0) {
            echo "No module changes detected."
            echo "CHANGED_MODULES=" >> $env:GITHUB_ENV
          } else {
            echo "Changed modules: $changedModules"
            echo "CHANGED_MODULES=$(($changedModules -join ','))" >> $env:GITHUB_ENV
          }
      - name: Development Build (if needed)
        working-directory: ./v1/views
        shell: pwsh
        run: |
          if ($env:CHANGED_MODULES -ne "") {
            Write-Host "Running Development Build..."
            pnpm run run-devone
          } else {
            Write-Host "No changes detected. Skipping Dev Build."
          }
      - name: Cache Development Build
        if: env.CHANGED_MODULES != ''
        uses: actions/cache@v3
        with:
          path: ./v1/views/*/src/public/
          key: ${{ runner.os }}-devbuild-${{ hashFiles('**/src/**/*.js', '**/src/**/*.ts', '**/package.json', 'webpack.config.js') }}
          restore-keys: |
            ${{ runner.os }}-devbuild-${{ github.run_id }}
            ${{ runner.os }}-devbuild-
      - name: Production Build (if needed)
        working-directory: ./v1/views
        shell: pwsh
        run: |
          if ($env:CHANGED_MODULES -ne "") {
            Write-Host "Running Production Build..."
            pnpm run run-prod
          } else {
            Write-Host "No changes detected. Skipping Prod Build."
          }
      - name: Debug Production Files
        run: |
         Get-ChildItem -Path ./v1/packages/ -Recurse | Format-List
      - name: Cache Production Build
        if: env.CHANGED_MODULES != ''
        uses: actions/cache@v3
        with:
          path: ./v1/packages/
          key: ${{ runner.os }}-prodbuild-${{ hashFiles('**/src/**/*.js', '**/src/**/*.ts', '**/package.json', 'webpack.config.js') }}
          restore-keys: |
            ${{ runner.os }}-prodbuild-${{ github.run_id }}
            ${{ runner.os }}-prodbuild-
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-packages
          path: ./v1/packages/
          retention-days: 7

      - name: Archive development artifacts
        uses: actions/upload-artifact@v4
        with:
          name: development-builds
          path: ./v1/views/*/src/public/
          retention-days: 1

