name: BIS Trainer CI Pipeline

on:
  push:
    branches:
      - main
      - CICD_Branch1
  pull_request:
    branches:
      - CICD_Branch1

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      # Setting up pnpm
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.1
          run_install: false

      # Setting up the node 
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Start Application
        run: nohup pnpm start &

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: ./dist
          retention-days: 7
